# Generated by Django 4.1.7 on 2023-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='delete',
            new_name='deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='mainapp.productattribute'),
        ),
    ]
