# Generated by Django 4.1.7 on 2023-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_delete_productcategory_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='deleted',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
