# Generated by Django 4.1.7 on 2023-02-15 12:21

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_productcategory_deleted_product_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=mainapp.models.products_avatars_path),
        ),
    ]
